version: '3.1'

services:
  webpack_web:
    build:
      context: ../
      dockerfile: docker/dockerfile
    image: webpack_web
    container_name: webpack_web
    volumes:
      - $PWD:/home/www/webpack-01
    ports:
      - 8080:80
    environment:
      - docker_port=80
    restart: unless-stopped
    tty: true
    privileged: true
    # command
  webpack_nginx:
    image: nginx
    container_name: webpack_nginx
    depends_on:
      - webpack_web
    links:
      - webpack_web
    volumes:
      - ./nginx/webpack-nginx.conf:/etc/nginx/conf.d/default.conf
      # - ../../dist/:/usr/share/nginx/html/
      - ./nginx/log:/var/log/nginx:rw
    ports:
      - '0.0.0.0:80:80'
