FROM alpine
LABEL name="webpack-01" version="1.0.0"
ENV work_dir=/home/www/webpack-01
WORKDIR ${work_dir}

RUN apk add --update\
    # autoconf \
    # automake \
    # g++ \
    # libc6-compat \
    # libjpeg-turbo-dev \
    # libpng-dev \
    # make \
    nodejs nodejs-npm\
    dumb-init\
    && rm -fr /var/cache/apk/*

# ubuntu
# RUN apt-get update\
#     && apt-get install -y curl \
#     && curl -sL https://deb.nodesource.com/setup_8.x | bash - \
#     && apt-get install -y\
#     nano\
#     tree\
#     nodejs\
#     dumb-init\
#     && apt-get clean \
#     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


COPY package.json .

# RUN npm install

EXPOSE ${docker_port}

ENTRYPOINT [ "/usr/bin/dumb-init" ]

CMD npm run dev
