version: '3.1'
services:
  mynginx:
    image: nginx
    container_name: mynginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../../dist/:/usr/share/nginx/html/
      - ./log:/var/log/nginx:rw
    ports:
      - '0.0.0.0:80:80'
