version: '3.1'
services:
  webpack_nginx:
    image: nginx
    container_name: webpack_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../../dist/:/usr/share/nginx/html/
      - ./log:/var/log/nginx:rw
    ports:
      - '8082:80'
    restart: unless-stopped
